services:

  # https://examples.bootstrap-table.com/#welcomes/from-url.html
  app:
    build:
      context: ./src
    container_name: app
    environment:
      - API_URL=http://api:5000/api/Book
    healthcheck:
      test: /healthchecks/curl.sh
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - ./healthchecks:/healthchecks
    ports:
      - 3000:80
    depends_on:
      api:
        condition: service_healthy

  ## Data API builder (DAB)
  # https://github.com/Azure/data-api-builder
  api:
    build:
      context: dab
    container_name: api
    environment:
      - DOTNET_EnableDiagnostics=0
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_hostBuilder__reloadConfigOnChange=true
      - CONNECTION_STRING=Host=db;Database=dab;username=postgres;password=
    healthcheck:
      test: ["CMD-SHELL", "curl -o /dev/null --fail localhost:5000/ || exit 1"]
      interval: "30s"
    #command: --ConfigFileName /App/dab-config.json
    #volumes:
    #  - ${PWD}/dab/config.json:/App/dab-config.json
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    restart: always
    container_name: db
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dab
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/library.postgresql.sql:/docker-entrypoint-initdb.d/data.sql
      - ./healthchecks:/healthchecks
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    name: dab-postgresql
