services:
  db:
    image: postgres:latest
    restart: always
    container_name: db
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "30s"
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDB}
    networks:
      - dab-pg
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/library.postgresql.sql:/docker-entrypoint-initdb.d/data.sql
      - db-data:/var/lib/postgresql/data
      - ./healthchecks:/healthchecks    

  #dab:
  #  image: "mcr.microsoft.com/azure-databases/data-api-builder:latest"
  #  container_name: dab
  #  ports:
  #    - "5000:5000"
  #  volumes:
  #    - ./dab-config.PostgreSql.json:/App/dab-config.json       
  #  networks:
  #    - dab-pg

volumes:
  db-data:
    name: dab-postgresql

networks:
  dab-pg:
    name: dab-postgresql
