services:
  app:
    build:
      context: app
    image: atrakic/dab/app
    container_name: app
    restart: on-failure
    environment:
      - API_URL=http://dab:5000/api/Book
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost || exit 1"]
      interval: "30s"
    ports:
      - 3000:80
    depends_on:
      dab:
        condition: service_healthy
  ## Data API builder (DAB)
  # https://github.com/Azure/data-api-builder
  dab:
    build:
      context: dab
    image: atrakic/dab/backend
    command: --ConfigFileName /App/dab-config.json
    container_name: dab
    ports:
      - "5000:5000"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_EnableDiagnostics=0
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_hostBuilder__reloadConfigOnChange=false
      - CONNECTION_STRING=Host=db;Database=dab;username=postgres;password=
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:5000/api/Book || exit 1"]
      interval: "30s"
    volumes:
      - ${PWD}/config.json:/App/dab-config.json
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:alpine
    restart: always
    container_name: db
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dab
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/library.postgresql.sql:/docker-entrypoint-initdb.d/data.sql
      - ./healthchecks:/healthchecks
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
    name: dab-postgresql
