ARG VERSION=6.0
FROM --platform=amd64 mcr.microsoft.com/dotnet/sdk:${VERSION}
LABEL org.opencontainers.image.source="https://github.com/atrakic/dab-postgresql"
RUN dotnet tool install --global Microsoft.DataApiBuilder
ENV PATH="$PATH:/root/.dotnet/tools"
