FROM mcr.microsoft.com/azure-databases/data-api-builder:latest
LABEL org.opencontainers.image.description="Custom Data Api Builder image"
LABEL org.opencontainers.image.source="https://github.com/atrakic/dab-postgresql"
RUN apt-get update && apt-get install -y curl && apt-get clean
